settings:
  title: 'Server Status Page'
  url: 'https://status.bradarr.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Servers Operational'
  notAllmonitorsOperational: 'Some Servers Not Operational'
  monitorLabelOperational: 'Healthy'
  monitorLabelNotOperational: 'Not Healthy'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mc.bradarr.com
    name: Main Server (mc.bradarr.com:25565)
    description: 'Vanilla 1.19.2'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: bedrock.bradarr.com
    name: Main Server Bedrock Compatible (bedrock.bradarr.com:25565)
    description: 'Vanilla 1.19.2'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: slimefun.bradarr.com
    name: Slimefun Server (slimefun.bradarr.com:25565)
    description: 'Vanilla 1.19.2'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: farmvalley.bradarr.com
    name: Farming Valley Server [Modded] (farmvalley.bradarr.com:25570)
    description: 'Farming Valley 1.0.8'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: pixelmon.bradarr.com
    name: Pixelmon Server [Modded] (pixelmon.bradarr.com:25572)
    description: 'Pixelmon 9.0.11'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: Oracle-Micro-2-Waterfall
    name: Waterfall Proxy 2
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: Oracle-Micro-1-Waterfall
    name: Waterfall Proxy 1
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: bradarr.apexmc.co
    name: Apex Proxy Main (bradarr.apexmc.co:25690)
    description: 'Vanilla 1.19.2'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: bradarr2.apexmc.co
    name: Apex Proxy Backup (bradarr2.apexmc.co:25774)
    description: 'Vanilla 1.19.2'
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: LocalReverseProxy
    name: General Reverse Proxy
    url: 'https://blog.cloudflare.com/'
    method: WEBHOOK
    linkable: false # allows the title to be a link, default=true

  - id: bradarr-website # unique identifier
    name: www.bradarr.com
    description: 'Bradarr Main Site' # default=empty
    url: 'https://www.bradarr.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bradarr-status-page # unique identifier
    name: status.bradarr.com
    description: 'Bradarr Status Page' # default=empty
    url: 'https://status.bradarr.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true