name = "bradarr-status-page"
workers_dev = true
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2022-11-22"

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
